retrieve_blog_task:
  description: >
    Retrieve blogs related to the given topic {topic} using advanced search tools.
    Ensure that the retrieved content is accurate, relevant, and up-to-date for the {date}.
  expected_output: >
    A list of links to 10 high-quality blog posts with a brief summary for each {topic}.
  agent: retrieve_blog

website_scraper_task:
  description: >
    Scrape specific information or data from a provided website URL.
    Ensure the scraped data is accurate, properly structured, and clean.
  expected_output: >
    Fully scrapped website content with all the important information from the website.
  agent: website_scraper

blog_writer_task:
  description: >
    Write a detailed and engaging blog post on the given topic, ensuring it is informative and easy to read.
    Incorporate keywords and adhere to SEO best practices.
  expected_output: >
    A complete blog post, formatted in markdown, ready for publication.
  agent: blog_writer

file_writer_task:
  description: >
   Write the blog post into a file.
  expected_output: >
    A fully fledged blog post with all the information from the previous tasks into a file named ./news/{date}_blog_post.md
  agent: file_writer
